---
services:

  traefik-init:
    image: busybox
    volumes:
      - ./traefik:/traefik
    command: sh -c "touch /traefik/acme.json && chmod 600 /traefik/acme.json"

  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/certs"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=info"
      - "--log.format=json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/etc/traefik/certs:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
    environment:
      - TZ=${TZ}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.middlewares.dashboard-ipwhitelist.ipwhitelist.sourcerange=172.16.254.0/24"
      - "traefik.http.routers.dashboard.middlewares=dashboard-ipwhitelist@docker"
    depends_on:
      traefik-init:
        condition: service_completed_successfully
    restart: unless-stopped


  gitea:
    image: gitea/gitea:${GITEA_VERSION}
    container_name: gitea
    hostname: gitea
    depends_on:
      - gitea_db
    env_file:
      - .env
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - ROOT_URL=https://${GITEA_DOMAIN}/
      - SSH_DOMAIN=${GITEA_DOMAIN}
      - SSH_PORT=22
    ports:
      - "22:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=cloudflare"
      - "traefik.http.services.gitea.loadbalancer.server.port=80"
    restart: unless-stopped


  gitea_db:
    image: lscr.io/linuxserver/mariadb:${MYSQL_VERSION}
    container_name: gitea_db
    hostname: gitea_db
    env_file:
      - .env
    volumes:
      - ./gitea_db:/config
    restart: unless-stopped


  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zabbix-agent2
    ports:
      - "10050:10050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ZBX_SERVER_HOST=172.16.250.15
      - ZBX_HOSTNAME=ct-gitea
      - TZ=America/Argentina/Buenos_Aires
    restart: unless-stopped


secrets:
  cloudflare_dns_api_token:
    file: ./secrets/cloudflare_dns_api_token
